default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # 检查 merge conflict
      - id: check-merge-conflict
      # 检查 private key
      - id: detect-private-key

  # 将代码中的 python2 语法转换为 python3 语法
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.21.0
    hooks:
      - id: pyupgrade

  # black
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
    - id: black
      language_version: python3
      args: [--config=pyproject.toml]

  # isort
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: isort
        additional_dependencies: ["toml"]
        args: [--settings-path=pyproject.toml]
